name: Feature request
description: Suggest an idea for this project
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        - Write a descriptive feature request title above.
        - Look into existing issues to make sure that this suggestion has not been offered before.

  - type: textarea
    attributes:
      label: Feature description
      description: |
        Briefly describe your suggestion.
        You can include images or videos with drag and drop, and format code blocks or logs with <code>```</code> tags.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Implementation Ideas
      description: |
        If you have any ideas on how to implement this suggestion, you can describe them here.
    validations:
      required: false
